version: '3'
services:
  dragonfly-instance-0:
    container_name: "dragonfly-instance-0"
    image: 'ghcr.io/dragonflydb/dragonfly:v1.14.3-ubuntu'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
  dragonfly-instance-1:
    container_name: "dragonfly-instance-1"
    image: 'ghcr.io/dragonflydb/dragonfly:v1.14.3-ubuntu'
    ulimits:
      memlock: -1
    ports:
      - "6380:6379"
  dragonfly-instance-2:
    container_name: "dragonfly-instance-2"
    image: 'ghcr.io/dragonflydb/dragonfly:v1.14.3-ubuntu'
    ulimits:
      memlock: -1
    ports:
      - "6381:6379"
  redlock-service:
    container_name: "redlock-service"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dragonfly-instance-0
      - dragonfly-instance-1
      - dragonfly-instance-2
    ports:
      - "8080:8080"
